### PR TITLE
Set `mode-name' correctly

### PR DESCRIPTION
**Pull request by drvink**
This fixes an issue which would prevent other packages (rtags, csharp-mode,
others) from byte-compiling if `emacs-lisp-mode' was in the list of major mode
names to diminish.

### CODE REVIEW

**Comment by alezost** [comment]
Hello, sorry I don't understand the problem.  Could you give a recipe,
please?

The change you propose will lead to a "dimmed" name where it is not
desired.  For example, if you have:

``` elisp
(dim-major-names '((emacs-lisp-mode "EL")))
```

then when you open .el file and press `C-h m`, _Help_ buffer displays:

```
Emacs-Lisp mode defined in `lisp-mode.el':
```

while with your change it will be:

```
EL mode defined in `lisp-mode.el':
```

**Comment by drvink** [comment]
Sorry, here's how to reproduce the issue. Using unpatched `dim`, eval this:

``` elisp
(require 'dim)
(dim-major-names
   '((emacs-lisp-mode "Elisp")))
```

Then:

``` elisp
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
```

Then `M-x list-packages` and try installing `csharp-mode`. Notice the byte compilation failures. Now uninstall `csharp-mode`, apply this patch to `dim`, and reinstall `csharp-mode`--notice that it works.

**Comment by drvink** [comment]
Also, the current code in `dim` doesn't work--it still replaces the name with the user's specified name in `C-h m`. I don't think users will be confused by seeing the name they chose in the help buffer.

**Comment by alezost** [comment]
Hm, this is interesting, thanks.  Currently [MELPA is down](https://github.com/melpa/melpa/issues/4156) (at least for me), so I'll check it later.  But to be honest, this sounds almost improbable: I install/upgrade packages regularly (using [Quelpa](https://github.com/quelpa/quelpa/) though) and I have never seen what you describe.

**Comment by alezost** [comment]
OK, melpa is back for me.  And as expected I cannot reproduce:
`csharp-mode.el` compiled successfully.  I think there could be
something else in your .emacs that leads to the result you describe.
How did you find that the problem was in `dim`?

**Comment by drvink** [comment]
The problem goes away if I don't dim `emacs-lisp-mode` on both the Arch Linux package of Emacs and the Emacs I've built myself on Windows.

**Comment by drvink** [comment]
I figured out the issue. In `c-update-modeline` in `cc-cmds.el`:

``` elisp
(defun c-update-modeline ()
  (let ((fmt (format "/%s%s%s%s"
             (if c-electric-flag "l" "")
             (if (and c-electric-flag c-auto-newline)
             "a" "")
             (if c-hungry-delete-key "h" "")
             (if (and
              ;; subword might not be loaded.
              (boundp 'subword-mode)
              (symbol-value 'subword-mode))
             "w"
               "")))
        ;; FIXME: Derived modes might want to use something else
        ;; than a string for `mode-name'.
    (bare-mode-name (if (string-match "\\(^[^/]*\\)/" mode-name)
                (match-string 1 mode-name)
              mode-name)))
;;     (setq c-submode-indicators
;;    (if (> (length fmt) 1)
;;        fmt))
    (setq mode-name
      (if (> (length fmt) 1)
          (concat bare-mode-name fmt)
    bare-mode-name))
    (force-mode-line-update)))
```

The binding for `bare-mode-name` should be:

``` elisp
(let ((bare-mode-name (if (and (stringp mode-name)
                               (string-match "\\(^[^/]*\\)/" mode-name))
                          (match-string 1 mode-name)
                        (format-mode-line mode-name))))
  ...)
```

There are a few other places in `cc-mode` that use `mode-name` incorrectly. I'll report it to the maintainers.

**Comment by alezost** [comment]
Wow, great investigation, thanks for letting me know!

**Comment by alezost** [comment]
Hey, I've just added `dim-everywhere` variable (commit 1106246), so as a
workaround for this issue you can use `(setq dim-everywhere t)`.

BTW could you give a link to the Emacs bug report (if you made it).
It may be useful for future reference, thanks!

**Comment by drvink** [comment]
Thanks! I'll give you a link to the bug report when I file it (it'll be against `cc-mode`, which has its own source repo and bug queue).

**Pull request closed without merging**
